### ISSUE TITLE
filename in OpenListOfImages-macro only set once

### ISSUE THREAD

**Issue by niederle** [stoeter/Fiji-Tools-for-HCS#5]
to me line 81 makes not much sense as the filename is only retrieved for the first image loaded but not for the rest:
[https://github.com/stoeter/Fiji-Tools-for-HCS/blob/master/ImageFileFilter/Macro_ImageFileFilter_Open_List_Of_Images.ijm](url)

**Comment by stoeter** [comment]
File name should always be retrieved.
Fixed with 2fa114e9
